name: Run Scraper Every Minute

on:
  schedule:
    - cron: "*/5 * * * *" # Try every 5 minutes for testing

jobs:
  scrape_job:
    runs-on: ubuntu-latest
    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      TO_ADDRESS: ${{ secrets.TO_ADDRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run scraping script
        run: node index.js
